Repository MrOliveGreen/PancakeswapFarmBot, pull requests merged in 2023-09, with the labels that each got.

#7 update: monitorPositions for autoremove & autoswap
  backend/controllers/botController.ts
  backend/controllers/functions.ts
  backend/controllers/walletController.ts
  backend/models/myposition.js
  backend/package.json
  backend/pnpm-lock.yaml
Labels: enhancement

#8 update: add auto create position feature
  backend/controllers/botController.ts
  backend/controllers/priceController.ts
  backend/controllers/walletController.ts
  backend/models/index.js
  backend/models/swap.js
Labels: enhancement

#9 Backend
  backend/controllers/walletController.ts
  backend/models/swap.js
Labels: bug

#10 update: frontend
  backend/controllers/positionController.ts
  backend/routes.js
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/Api.js
  client/src/App.css
  client/src/Main.js
  client/yarn.lock
Labels: enhancement

#11 update: push
  client/public/favicon.ico
  client/public/favicon.png
  client/public/index.html
  client/src/Main.js
Labels: bug, enhancement

#12 fix: auto stake wait transaction receipt
  backend/controllers/botController.ts
Labels: enhancement

#13 fix: check transaction receipt success
  backend/controllers/botController.ts
  backend/controllers/walletController.ts
Labels: enhancement

#14 update: frontend
  client/src/App.css
  client/src/Main.js
Labels: bug
